<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-PLQ0LQG" name="datadriven.TC006_MS_DataDrivenFromExcelLoginTest" tests="1" failures="0" timestamp="01 May 2022 22:33:55 GMT" time="0.000" errors="1">
  <testcase name="LoginValidationTest" time="0.000" classname="datadriven.TC006_MS_DataDrivenFromExcelLoginTest">
    <error type="org.testng.TestNGException" message="
Cannot instantiate class util.XLUtility">
      <![CDATA[org.testng.TestNGException: 
Cannot instantiate class util.XLUtility
at org.testng.internal.ClassHelper.newInstance(ClassHelper.java:71)
at org.testng.internal.Parameters.findDataProvider(Parameters.java:582)
at org.testng.internal.Parameters.findDataProvider(Parameters.java:509)
at org.testng.internal.Parameters.handleParameters(Parameters.java:691)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:49)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:37)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:924)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.InstantiationException: util.XLUtility
at java.lang.Class.newInstance(Class.java:427)
at org.testng.internal.ClassHelper.newInstance(ClassHelper.java:69)
... 23 more
Caused by: java.lang.NoSuchMethodException: util.XLUtility.<init>()
at java.lang.Class.getConstructor0(Class.java:3082)
at java.lang.Class.newInstance(Class.java:412)
... 24 more
]]>
    </error>
  </testcase> <!-- LoginValidationTest -->
</testsuite> <!-- datadriven.TC006_MS_DataDrivenFromExcelLoginTest -->
